### ISSUE TITLE
generate_ONet_data.py

### ISSUE THREAD

**Issue by Baishi03** [yeyupiaoling/PaddlePaddle-MTCNN#3]
您好，我今天运行generate_ONet_data.py的报错了
neg数量：0 pos数量：0 part数量:0 这些为什么为空呀？

aistudio@jupyter-243010-324479:~$ python PaddlePaddle-MTCNN/train/generate_ONet_data.py
开始生成bbox图像数据
  0%|                                                                                           | 0/12880 [00:00<?, ?it/s]W0317 22:05:34.145320   996 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0317 22:05:34.149135   996 device_context.cc:245] device: 0, cuDNN Version: 7.3.
100%|███████████████████████████████████████████████████████████████████████████████| 12880/12880 [12:15<00:00, 17.52it/s]
12880it [00:00, 170336.20it/s]
开始生成landmark图像数据
100%|██████████████████████████████████████████████████████████████████████████████| 10000/10000 [01:21<00:00, 122.20it/s]
开始合成数据列表
整理前的数据：neg数量：0 pos数量：0 part数量:0 landmark: 178719 基数:1000
Traceback (most recent call last):
  File "PaddlePaddle-MTCNN/train/generate_ONet_data.py", line 223, in <module>
    combine_data_list(os.path.join(data_path, '48'))
  File "/home/aistudio/PaddlePaddle-MTCNN/train/utils.py", line 138, in combine_data_list
    neg_kerep = npr.choice(len(neg), size=base_num * 3, replace=base_num * 3 > len(neg))
  File "mtrand.pyx", line 1119, in mtrand.RandomState.choice
ValueError: 'a' must be greater than 0 unless no samples are taken

**Comment by Baishi03** [comment]
我对0%这块儿其实很奇怪，希望您能解答一下为什么会这样？
aistudio@jupyter-243010-324479:~$ python PaddlePaddle-MTCNN/train/generate_ONet_data.py
开始生成bbox图像数据
  0%|                                                                                           | 0/12880 [00:00<?, ?it/s]W0320 16:11:15.065244   118 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0320 16:11:15.069579   118 device_context.cc:245] device: 0, cuDNN Version: 7.3.
100%|███████████████████████████████████████████████████████████████████████████████| 12880/12880 [12:44<00:00, 16.86it/s]
12880it [00:00, 171374.76it/s]

**Comment by Baishi03** [comment]
我读取了generate_ONet_data.py产生的detections.pkl文件，里面全部为空数组。
说明识别结果为空。麻烦咨询一下，您当时是怎么解决这个问题的呀？
